language: php
php:
- 7.2
- nightly
before_install:
- openssl aes-256-cbc -K $encrypted_845395c4607a_key -iv $encrypted_845395c4607a_iv
  -in brahmaos.pem.enc -out ~/.ssh/brahmaos.pem -d
- chmod 600 ~/.ssh/brahmaos.pem
- echo -e "Host tokyo\n\thostname ${hostname_tokyo}\n\tport ${port_tokyo}\n\tuser ${user_tokyo}\n\tIdentityFile  ~/.ssh/brahmaos.pem\nHost london\n\thostname ${hostname_london}\n\tport ${port_london}\n\tuser ${user_london}\n\tIdentityFile  ~/.ssh/brahmaos.pem" > ~/.ssh/config
- cat ~/.ssh/config
after_success:
- ssh tokyo "sudo cd /www/brahmaos.io/ && sudo git pull"
- ssh london "sudo cd /www/brahmaos.io/ && sudo git pull"
env:
- APP_DEBUG=false
addons:
  ssh_known_hosts:
  - 13.230.159.122
  - 159.65.22.214
