language: php
php:
- 7.2
- nightly
before_install:
- openssl aes-256-cbc -K $encrypted_845395c4607a_key -iv $encrypted_845395c4607a_iv
  -in brahmaos-tokyo.pem.enc -out ~/.ssh/brahmaos-tokyo.pem -d
- openssl aes-256-cbc -K $encrypted_845395c4607a_key -iv $encrypted_845395c4607a_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- chmod 600 ~/.ssh/brahmaos-tokyo.pem
- echo "Host tokyo
        	    hostname ${hostname_tokyo}
                port ${port_tokyo}
                user ${user_tokyo}
                IdentityFile  ~/.ssh/brahmaos-tokyo.pem
        Host london
                hostname ${hostname_london}
                port ${port_london}
                user ${user_london}
                IdentityFile  ~/.ssh/id_rsa" > ~/.ssh/config
after_success:
- ssh tokyo "sudo su - && cd /www/test && git pull"
- ssh london "sudo su - && cd /www/test && git pull"

env:
- APP_DEBUG=false
addons:
  ssh_known_hosts: 35.201.219.121
