@extends('site2.abstract')

@section("docs-content")
<div>
        <!-- background -->
        <h1 id="Background">Background</h1>

        <p>Blockchain technology is known through the birth of bitcoin in 2008.
            Since then developers and entrepreneurs have been experimenting with this technology
            in hopes of using it in a broader range of products to solve the technical pain points in different Industry.
        </p>

        <p>
            Blockchain technology is fundamentally not a technology that solves technical pain points for companies in existing corporate structures.
            Instead, it is dealing with a network of self-governing,
            non-central value networks that sustain a network through incentives Safe, continuous operation.
        </p>

        <p>
            Ethernet brings the potential for non-stop applications by proposing an architecture for smart contracts.
            In just a short time of 2017, revolutionary solutions and implementations such as the Kyber Network, 0x Protocol,
            and Radian Network emerged over the Ethernet network,
            bringing a completely centerless application ecosystem to the future Prospects and expectations.
        </p>

        <p>
            At the same time, many other applications can carry the public chain is also emerging,
            such as EOS or ADA.As an electronic device such as a mobile phone that takes up the largest number of users and takes the longest time,
            it still runs an OS that relies on a central service,
            from user account systems to personal data backups to application build logic over OSs. Apparently,
            some OS does not provide a complete foundation for the future application of the blockchain.
        </p>


        <br>
        <!-- Decentralized OS Demand -->
        <h1 id="DecentralizedOSDemand">Decentralized OS Demand</h1>
        <p>
            Unlike the current operating iOS and Android OS,
            decentralized OS requires complete removal of the central server design architecture at the beginning of the design,
            from basic services to upper-level application builds.
            While ensuring that UI / UX levels maintain their usage habits as much as possible,
            we pay more attention to the value and value that central services can play in the OS.
        </p>

        <br>
        <!-- Data Privacy -->
        <h3 id="DataPrivacy">Data Privacy</h3>
        <p>
            When using an OS, it is valuable whether the data is intentionally generated by the user or generated by an inadvertent operation
        </p>

        <p>
            Such data forms the basis of artificial intelligence analysis and is called factual data.
            With the same factual data, different user portraits can be generated after data mining algorithms are continuously optimized.
            Moreover, all the personal services we know today such as online shopping recommendations, friend recommendations or voice recognition,
            rely on user portraits generated by user's factual data.
            These factual data by billions of users makes it possible for the commercial empire like Facebook or Google established.
        </p>

        <p>
            However, in the commercial closed loop of centralized services,
            users do not get financially rewarded except for contributing their actions and factual data. Moreover,
            these data can be sold to others. In a way,
            business models for systems and App vendors are now mainly based on the use of user privacy data without financial rewards.
        </p>

        <p>
            In Brahma OS privacy issues will be fundamentally solved.
            The act of stealing and exploiting user privacy data will become difficult to perform.
        </p>

        <br>
        <!--  Accessible Network Communication -->
        <h3 id="AccessibleNetworkCommunication"> Accessible Network Communication</h3>
        <p> Whether in the blockchain or the current Internet economy,
            network communication connections are issues that need to be resolved first.
            How to access data on the web without any problems has become a crucial issue in many cases.
        </p>

        <p>
            When we talk about network communications,
            most of the time we are talking about how the terminal connects to a wide area network.
            In the current architecture, the terminal device connects to the meta-network (i.e., the local area network to which it can connect directly).
            Then meta-network connects to different meta-network or the upper network through the router and switch.
            Most of the connections between different meta-networks are operators.We can then talk about meta-network and router.
        </p>

        <p>
            The end nodes in the meta-network can form a peer-to-peer network,
            that is, the nodes in any meta-network are offline and should not cause unreachable communication in the meta-network.
            This is not the core of our concern, as its connectivity problems are not hard to solve.
            The critical problem goes to the router.
        </p>

        <p>
            In current network communications, we must trust and can only trust the router.
            In fact, it not only can completely intercept and spy on the data, protocol,
            and trend of communication between meta-networks but also act on it, such as tampering and denial of service.
        </p>
        <p>

            In currently available network communications,
            operating system end-users face two major problems: privacy exposure, unprotected accessibility.
        </p>

        <p>
            Therefore, in the Brahma OS,
            we expect to build a peer-to-peer OS network to ensure the encryption of the communication data
            and the non- identifiability of communication data through protocol confusion at the data
            transport level, and to build an autonomous connected network based on the configuration of the routing.
        </p>

        <br>
        <!--Decentralized Storage-->
        <h3 id="DecentralizedStorage"> Decentralized Storage</h3>
        <p>
            Today, most of the OS provides users with the cloud storage function.
            Users in different devices only need to log in to the same account to have access to the same data.
            Cloud storage brings users personal convenience. At the same time,
            it can also bring some potential trouble for personal data security.
        </p>
        <p>
            Dropbox loopholes lead to loss of personal data.
            Many nude photos of some celebrities were leaked when the iCloud account was attacked by lots of hackers.
            Incidents like these events have reflected the apparent problem: in the current centralized cloud storage architecture,
            It is only a matter of time before the security problem is revealed, in other words,
            there is a systematic risk that can not be avoided.
        </p>
        <p>
            Decentralized chain storage avoids this kind of problem from the very beginning of the design.
            Taking IPFS as an example, the decentralized storage has no single server that can be attacked or a group of servers that can be traced.
            All data are divided into multiple parts, randomly stored in different nodes of the network.
            The entire network is safe and efficient for storage and transmission by miners in storage networks.
        </p>

        <p>
            When building storage services, Brahma OS uses directly decentralized web services. For now,
            we do not guarantee the use of IPFS. We would compare other potential decentralized storage like Sia, Storj, MaidSafe.
        </p>

        <br>
        <!-- Management of Cryptographic Assets  -->
        <h3 id="ManagementofCryptographicAssets">Management of Cryptographic Assets</h3>
        <p>
            Wallet application layer needs to complete the function of asset
            management. We consider this requirement from the OS's perspective.
        </p>

        <p>
            In the foreseeable future, cryptographic assets would be less dependent on centralized exchanges.
            The role of centralized exchanges transforms from the current speculative trading into connecting blockchain assets and legal assets.
            Cryptographic assets exchange can be completed directly using decentralized services.
        </p>

        <p>
            Now, based on the backbone of Ethereum,
            we have been able to provide service by building transaction relayer with the 0x protocol.
            This protocol can connect all the other built replayer.
            That is, it does not only provide liquidity within a single application but the asset liquidity among all replayer using this protocol.
        </p>

        <p>
            Another possible solution is through Kyber Network.
            Unlike Ox, Kyber Network itself can serve as a decentralized exchange.
            An exchange or convert request can be executed immediately within a single transaction without a relayer.
        </p>

        <p>
            Compared with available options of exchange service, it is necessary to construct exchange service from the OS-level.
            Brahma OS could be the carrier of many D-App. All consumption in D-App should be on-chain (rapid transactions off-chain would be on-chain eventually).
            In the process of a transaction, a payment request could be initiated by a D-App and goes directly to an end-user.
        </p>

        <br>
        <!--  Autonomous Economic System -->
        <h3 id="AutonomousEconomicSystem">Autonomous Economic System</h3>
        <p>
            From last year, there have been significant technological breakthroughs on Ethereum.
            These breakthroughs bring closer the blockchain and users one to another.
        </p>

        <p>
            In the initial stage, Brahma OS provided autonomous unobstructed network communication service and foundation of the upper application services by
            integrating technical solutions such as IPFS, Kyber Network, and 0x. With the cross-link technology and Brahma OS backbones,
            we will build a complete ecosystem based on the Brahma OS chain that connects other backbones such as ETH, EOS, and ADA.
        </p>
</div>
@endsection